# Generated by Django 5.0.3 on 2024-04-16 05:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50, null=True)),
                ('course_uuid', models.ForeignKey(db_column='course_uuid', on_delete=django.db.models.deletion.CASCADE, to='forge.course')),
                ('user_uuid', models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_courses',
            },
        ),
    ]
