# Generated by Django 5.0.3 on 2024-04-15 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author_uuid',
            field=models.ForeignKey(db_column='author_uuid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='course_uuid',
            field=models.ForeignKey(db_column='course_uuid', on_delete=django.db.models.deletion.CASCADE, to='store.course'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user_uuid',
            field=models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='usercourse',
            table='user_courses',
        ),
    ]
