# Generated by Django 5.0.3 on 2024-04-22 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0002_alter_course_status'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user_uuid', 'course_uuid')},
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['user_uuid'], name='user_course_user_uu_042ecd_idx'),
        ),
    ]
