# Generated by Django 5.0.3 on 2024-05-27 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_transactionsdetails_course_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('error', 'Error'), ('by_admin', 'By_Admin')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='transaction_uuid',
            field=models.ForeignKey(db_column='transaction_uuid', null=True, on_delete=django.db.models.deletion.PROTECT, to='store.transactionsdetails'),
        ),
    ]
