# Generated by Django 5.0.3 on 2024-04-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_course_author_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
    ]
