# Generated by Django 5.0.3 on 2024-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0003_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('moderation', 'Moderation'), ('passed', 'Passed'), ('fail', 'Fail'), ('published', 'Published'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
    ]
